const fs = require('fs');

const toolsPath = 'src/data/toolsData.js';
let content = fs.readFileSync(toolsPath, 'utf8');

// 1. Set isOpenWeights: true for openhands, crewai, and autogpt
content = content.replace(
  /("id":\s*"openhands"[\s\S]*?"isOpenWeights":\s*)false/,
  '$1true'
);
content = content.replace(
  /("id":\s*"crewai"[\s\S]*?"isOpenWeights":\s*)false/,
  '$1true'
);
content = content.replace(
  /("id":\s*"autogpt"[\s\S]*?"isOpenWeights":\s*)false/,
  '$1true'
);

// 2. Prepare the 9 new open source tools
const newTools = [
  {
    id: "comfyui",
    slug: "comfyui",
    name: "ComfyUI",
    org: "Comfy Org",
    category: "Image Generation",
    entityType: "tool",
    rank: 21,
    rankDelta: "+4",
    superpower: "Modular Graph Synthesis",
    superpowerShort: "Node Workflows",
    superpowerDetail: "Node-based generative diffusion pipeline",
    isOpenWeights: true,
    licenseType: "GPL-3.0",
    license: "GPL-3.0",
    arenaElo: null,
    eloChange: null,
    categoryMetricLabel: "Tool Rating",
    categoryMetricValue: "4.9 / 5.0",
    categorySubMetricLabel: "Render Time",
    categorySubMetricValue: "Instant / GPU",
    categoryDimension3: "Modular Graph",
    mmluPro: "N/A",
    codingScore: "N/A",
    mathScore: "N/A",
    monthlyVisits: "18.5M",
    growth: "+52.0%",
    growthTrend: "up",
    price: "Free / Open Source",
    outputSpeed: "GPU Bound",
    speedNum: 95,
    contextWindow: "Full graph execution",
    badge: "Open Source",
    shortDescription: "Powerful and modular node-based graphical interface for Stable Diffusion, FLUX, and generative AI pipelines.",
    fullDescription: "ComfyUI lets users design and execute advanced image and video generation graphs with granular control over SDXL, FLUX, LoRAs, and ControlNets.",
    website: "https://github.com/comfyanonymous/ComfyUI",
    logoText: "ComfyUI",
    logoColor: "#10B981",
    releaseDate: "January 2023",
    source: "Open Source Telemetry & GitHub",
    lastUpdated: "March 2026",
    keyFeatures: [
      "Node-based workflow builder for FLUX and SDXL",
      "ControlNet, IP-Adapter, and LoRA chaining",
      "Memory-efficient GPU tensor offloading",
      "High-throughput API execution mode"
    ],
    benchmarks: [
      { name: "Workflow Flexibility Score", score: "98.5%", rank: "#1 Node UI" },
      { name: "VRAM Optimization", score: "Low VRAM", rank: "Top Tier" }
    ],
    specs: {
      inputPrice: "Free Open Source",
      outputPrice: "Self-hosted hardware",
      contextWindow: "Multi-model graphs",
      maxOutput: "Arbitrary resolution",
      cutoff: "Local execution",
      modalities: "Image, Video, Audio",
      speed: "Dependent on local GPU",
      ttft: "50ms"
    }
  },
  {
    id: "automatic1111-sd-webui",
    slug: "automatic1111-sd-webui",
    name: "Automatic1111 (SD WebUI)",
    org: "AUTOMATIC1111",
    category: "Image Generation",
    entityType: "tool",
    rank: 22,
    rankDelta: "+1",
    superpower: "WebUI Diffusion Hub",
    superpowerShort: "SD WebUI",
    superpowerDetail: "Standard interface for local diffusion models",
    isOpenWeights: true,
    licenseType: "AGPL-3.0",
    license: "AGPL-3.0",
    arenaElo: null,
    eloChange: null,
    categoryMetricLabel: "Tool Rating",
    categoryMetricValue: "4.8 / 5.0",
    categorySubMetricLabel: "Render Time",
    categorySubMetricValue: "Instant / GPU",
    categoryDimension3: "WebUI / Extensions",
    mmluPro: "N/A",
    codingScore: "N/A",
    mathScore: "N/A",
    monthlyVisits: "25.0M",
    growth: "+12.0%",
    growthTrend: "up",
    price: "Free / Open Source",
    outputSpeed: "GPU Bound",
    speedNum: 90,
    contextWindow: "Full prompt embeddings",
    badge: "Open Source",
    shortDescription: "The definitive open-source web browser interface for Stable Diffusion and SDXL image synthesis.",
    fullDescription: "AUTOMATIC1111 Stable Diffusion WebUI is the ecosystem standard for self-hosted image generation with deep extension support, inpainting, and outpainting.",
    website: "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
    logoText: "A1111",
    logoColor: "#F59E0B",
    releaseDate: "August 2022",
    source: "Open Source Telemetry & GitHub",
    lastUpdated: "March 2026",
    keyFeatures: [
      "Comprehensive txt2img, img2img, and inpainting",
      "Extensive ecosystem of community extensions",
      "Prompt weighting and negative prompt scheduling",
      "LoRA and textual inversion integration"
    ],
    benchmarks: [
      { name: "Community Adoption", score: "140k+ Stars", rank: "#1 Most Cloned" }
    ],
    specs: {
      inputPrice: "Free Open Source",
      outputPrice: "Self-hosted hardware",
      contextWindow: "77 token CLIP embeddings",
      maxOutput: "2048x2048 Hi-Res Fix",
      cutoff: "Local execution",
      modalities: "Image",
      speed: "Dependent on local GPU",
      ttft: "100ms"
    }
  },
  {
    id: "fooocus",
    slug: "fooocus",
    name: "Fooocus",
    org: "lllyasviel",
    category: "Image Generation",
    entityType: "tool",
    rank: 23,
    rankDelta: "+3",
    superpower: "Midjourney-like Simplicity",
    superpowerShort: "Fooocus Gen",
    superpowerDetail: "Automated prompt enhancements and SDXL tuning",
    isOpenWeights: true,
    licenseType: "GPL-3.0",
    license: "GPL-3.0",
    arenaElo: null,
    eloChange: null,
    categoryMetricLabel: "Tool Rating",
    categoryMetricValue: "4.8 / 5.0",
    categorySubMetricLabel: "Render Time",
    categorySubMetricValue: "Fast / GPU",
    categoryDimension3: "Prompt Engine",
    mmluPro: "N/A",
    codingScore: "N/A",
    mathScore: "N/A",
    monthlyVisits: "8.5M",
    growth: "+34.0%",
    growthTrend: "up",
    price: "Free / Open Source",
    outputSpeed: "GPU Bound",
    speedNum: 92,
    contextWindow: "Dynamic style prompts",
    badge: "Open Source",
    shortDescription: "Image generating software that re-thinks the designs of Stable Diffusion and Midjourney for streamlined simplicity.",
    fullDescription: "Fooocus is an open-source image generation interface that automates complex technical parameters, providing Midjourney-level aesthetics with local SDXL models.",
    website: "https://github.com/lllyasviel/Fooocus",
    logoText: "Fooocus",
    logoColor: "#EC4899",
    releaseDate: "August 2023",
    source: "Open Source Telemetry & GitHub",
    lastUpdated: "March 2026",
    keyFeatures: [
      "Midjourney-style prompt expansion and default aesthetics",
      "Built-in SDXL refiner and upscaling presets",
      "Image prompt (CPDS) and face swap capability",
      "Minimalist, zero-configuration setup"
    ],
    benchmarks: [
      { name: "Aesthetic Output Index", score: "94.2%", rank: "Top Tier" }
    ],
    specs: {
      inputPrice: "Free Open Source",
      outputPrice: "Self-hosted hardware",
      contextWindow: "Multi-style prompt expansions",
      maxOutput: "1792x1792 with upscaler",
      cutoff: "Local execution",
      modalities: "Image",
      speed: "Dependent on local GPU",
      ttft: "80ms"
    }
  },
  {
    id: "ollama",
    slug: "ollama",
    name: "Ollama",
    org: "Ollama",
    category: "Productivity",
    entityType: "tool",
    rank: 24,
    rankDelta: "+6",
    superpower: "Local LLM Runtime",
    superpowerShort: "Local Runtime",
    superpowerDetail: "One-command local model downloads and REST API",
    isOpenWeights: true,
    licenseType: "MIT",
    license: "MIT",
    arenaElo: null,
    eloChange: null,
    categoryMetricLabel: "Tool Rating",
    categoryMetricValue: "4.9 / 5.0",
    categorySubMetricLabel: "Adoption",
    categorySubMetricValue: "100k+ Stars",
    categoryDimension3: "REST API & CLI",
    mmluPro: "N/A",
    codingScore: "N/A",
    mathScore: "N/A",
    monthlyVisits: "32.0M",
    growth: "+88.0%",
    growthTrend: "up",
    price: "Free / Open Source",
    outputSpeed: "Local Hardware",
    speedNum: 105,
    contextWindow: "Model dependent",
    badge: "Open Source",
    shortDescription: "Get up and running with Llama 3, DeepSeek, Mistral, and other large language models locally.",
    fullDescription: "Ollama bundles model weights, configuration, and GPU acceleration into a unified CLI and OpenAI-compatible REST server for local development.",
    website: "https://ollama.com",
    logoText: "Ollama",
    logoColor: "#FFFFFF",
    releaseDate: "July 2023",
    source: "Open Source Telemetry & GitHub",
    lastUpdated: "March 2026",
    keyFeatures: [
      "One-command pull and run for Llama, DeepSeek, and Gemma",
      "OpenAI-compatible /v1 chat completions endpoint",
      "Native Apple Silicon, NVIDIA CUDA, and AMD ROCm support",
      "Modelfile customization for system prompts and parameters"
    ],
    benchmarks: [
      { name: "Developer Popularity", score: "105k+ Stars", rank: "#1 Local Runner" }
    ],
    specs: {
      inputPrice: "Free Open Source",
      outputPrice: "Self-hosted hardware",
      contextWindow: "Up to 128k context",
      maxOutput: "Streamed tokens",
      cutoff: "Local runtime",
      modalities: "Text, Vision (Llama 3.2 Vision)",
      speed: "Optimized llama.cpp backend",
      ttft: "20ms"
    }
  },
  {
    id: "vllm",
    slug: "vllm",
    name: "vLLM",
    org: "vLLM Project",
    category: "Coding / Developer",
    entityType: "tool",
    rank: 25,
    rankDelta: "+5",
    superpower: "PagedAttention Serving",
    superpowerShort: "PagedAttention",
    superpowerDetail: "High-throughput and memory-efficient LLM inference engine",
    isOpenWeights: true,
    licenseType: "Apache 2.0",
    license: "Apache 2.0",
    arenaElo: null,
    eloChange: null,
    categoryMetricLabel: "Tool Rating",
    categoryMetricValue: "4.9 / 5.0",
    categorySubMetricLabel: "Throughput",
    categorySubMetricValue: "24x Baseline",
    categoryDimension3: "PagedAttention",
    mmluPro: "N/A",
    codingScore: "N/A",
    mathScore: "N/A",
    monthlyVisits: "14.2M",
    growth: "+65.0%",
    growthTrend: "up",
    price: "Free / Open Source",
    outputSpeed: "Extreme Throughput",
    speedNum: 125,
    contextWindow: "Continuous batching",
    badge: "Open Source",
    shortDescription: "High-throughput and memory-efficient inference and serving engine for LLMs.",
    fullDescription: "vLLM utilizes PagedAttention to virtually eliminate memory fragmentation in KV cache, delivering industry-leading concurrency for enterprise deployments.",
    website: "https://github.com/vllm-project/vllm",
    logoText: "vLLM",
    logoColor: "#3B82F6",
    releaseDate: "June 2023",
    source: "Open Source Telemetry & UC Berkeley",
    lastUpdated: "March 2026",
    keyFeatures: [
      "PagedAttention with near-zero KV cache fragmentation",
      "Continuous batching of incoming parallel requests",
      "FP8, AWQ, and GPTQ quantization kernels",
      "Drop-in OpenAI API compatible server"
    ],
    benchmarks: [
      { name: "Serving Throughput", score: "24x HF TGI", rank: "#1 Throughput" }
    ],
    specs: {
      inputPrice: "Free Open Source",
      outputPrice: "Self-hosted hardware",
      contextWindow: "Arbitrary continuous batching",
      maxOutput: "High concurrent streams",
      cutoff: "Inference engine",
      modalities: "Text, Vision",
      speed: "Sub-millisecond token dispatch",
      ttft: "15ms"
    }
  },
  {
    id: "lm-studio",
    slug: "lm-studio",
    name: "LM Studio",
    org: "Element Labs",
    category: "Productivity",
    entityType: "tool",
    rank: 26,
    rankDelta: "+2",
    superpower: "Desktop LLM Sandbox",
    superpowerShort: "Desktop LLM",
    superpowerDetail: "Offline local model discovery, chat, and local server",
    isOpenWeights: true,
    licenseType: "Free Community",
    license: "Free Community / Open Ecosystem",
    arenaElo: null,
    eloChange: null,
    categoryMetricLabel: "Tool Rating",
    categoryMetricValue: "4.8 / 5.0",
    categorySubMetricLabel: "Ease of Use",
    categorySubMetricValue: "99.0%",
    categoryDimension3: "Desktop GUI",
    mmluPro: "N/A",
    codingScore: "N/A",
    mathScore: "N/A",
    monthlyVisits: "21.0M",
    growth: "+45.0%",
    growthTrend: "up",
    price: "Free",
    outputSpeed: "Local Hardware",
    speedNum: 98,
    contextWindow: "Configurable context",
    badge: "Popular",
    shortDescription: "Discover, download, and run local LLMs offline on Mac, Windows, and Linux.",
    fullDescription: "LM Studio is an intuitive desktop app for running GGUF models from Hugging Face with built-in GPU acceleration and a local developer server.",
    website: "https://lmstudio.ai",
    logoText: "LM Studio",
    logoColor: "#8B5CF6",
    releaseDate: "March 2023",
    source: "Developer Telemetry",
    lastUpdated: "March 2026",
    keyFeatures: [
      "Direct Hugging Face GGUF model search and download",
      "Hardware acceleration for Apple Metal and NVIDIA GPUs",
      "Local OpenAI-compatible inference server",
      "Side-by-side model chat comparison mode"
    ],
    benchmarks: [
      { name: "Desktop UX Satisfaction", score: "96.4%", rank: "Top Tier" }
    ],
    specs: {
      inputPrice: "Free",
      outputPrice: "Self-hosted hardware",
      contextWindow: "Model dependent GGUF",
      maxOutput: "Streamed tokens",
      cutoff: "Local desktop runtime",
      modalities: "Text, Vision",
      speed: "Optimized llama.cpp bindings",
      ttft: "30ms"
    }
  },
  {
    id: "dify-ai",
    slug: "dify-ai",
    name: "Dify",
    org: "LangGenius",
    category: "AI Agents",
    entityType: "tool",
    rank: 27,
    rankDelta: "+4",
    superpower: "Visual Agent Workflow",
    superpowerShort: "Agent Workflows",
    superpowerDetail: "Open-source LLM app development and RAG orchestrator",
    isOpenWeights: true,
    licenseType: "Apache 2.0",
    license: "Apache 2.0",
    arenaElo: null,
    eloChange: null,
    categoryMetricLabel: "Tool Rating",
    categoryMetricValue: "4.8 / 5.0",
    categorySubMetricLabel: "RAG Accuracy",
    categorySubMetricValue: "93.0%",
    categoryDimension3: "Visual Canvas",
    mmluPro: "N/A",
    codingScore: "N/A",
    mathScore: "N/A",
    monthlyVisits: "12.8M",
    growth: "+72.0%",
    growthTrend: "up",
    price: "Free / Open Source",
    outputSpeed: "Instant Canvas",
    speedNum: 96,
    contextWindow: "Hybrid RAG context",
    badge: "Open Source",
    shortDescription: "Open-source LLM app development platform combining AI workflow, RAG pipeline, and agent capabilities.",
    fullDescription: "Dify is an enterprise-ready visual development platform that coordinates multi-model routing, knowledge retrieval, and tool-augmented agents.",
    website: "https://dify.ai",
    logoText: "Dify",
    logoColor: "#2563EB",
    releaseDate: "May 2023",
    source: "Open Source Telemetry & GitHub",
    lastUpdated: "March 2026",
    keyFeatures: [
      "Visual orchestration canvas for multi-agent workflows",
      "End-to-end RAG pipeline with hybrid keyword/vector search",
      "Observability, prompt evaluation, and user analytics",
      "Integration with dozens of model providers and vector databases"
    ],
    benchmarks: [
      { name: "Agent Flow Success", score: "92.8%", rank: "Top Tier" }
    ],
    specs: {
      inputPrice: "Free Open Source",
      outputPrice: "Self-hosted hardware",
      contextWindow: "Unlimited multi-doc vector indexing",
      maxOutput: "Structured workflow output",
      cutoff: "Active platform",
      modalities: "Text, Vision, Document Parsing",
      speed: "Low-latency orchestration",
      ttft: "120ms"
    }
  },
  {
    id: "langfuse",
    slug: "langfuse",
    name: "Langfuse",
    org: "Langfuse",
    category: "Coding / Developer",
    entityType: "tool",
    rank: 28,
    rankDelta: "+3",
    superpower: "Open LLM Engineering",
    superpowerShort: "LLM Observability",
    superpowerDetail: "Tracing, prompt management, and evaluation suite",
    isOpenWeights: true,
    licenseType: "MIT",
    license: "MIT",
    arenaElo: null,
    eloChange: null,
    categoryMetricLabel: "Tool Rating",
    categoryMetricValue: "4.9 / 5.0",
    categorySubMetricLabel: "Trace Latency",
    categorySubMetricValue: "<2ms overhead",
    categoryDimension3: "Telemetry",
    mmluPro: "N/A",
    codingScore: "N/A",
    mathScore: "N/A",
    monthlyVisits: "6.5M",
    growth: "+84.0%",
    growthTrend: "up",
    price: "Free / Open Source",
    outputSpeed: "Ultra-low Overhead",
    speedNum: 115,
    contextWindow: "Full trace payload",
    badge: "Open Source",
    shortDescription: "Open-source LLM engineering platform for observability, tracing, evaluations, and prompt management.",
    fullDescription: "Langfuse provides production teams with granular nested traces, cost tracking per model invocation, and automated benchmark scoring.",
    website: "https://langfuse.com",
    logoText: "Langfuse",
    logoColor: "#059669",
    releaseDate: "September 2023",
    source: "Open Source Telemetry & GitHub",
    lastUpdated: "March 2026",
    keyFeatures: [
      "Detailed nested tracing for complex agent chains",
      "Cost, latency, and token attribution per customer and model",
      "Prompt management with programmatic version control",
      "Automated evaluation metrics and human-in-the-loop scoring"
    ],
    benchmarks: [
      { name: "Telemetry Overhead", score: "<2ms", rank: "#1 Low Overhead" }
    ],
    specs: {
      inputPrice: "Free Open Source",
      outputPrice: "Self-hosted hardware",
      contextWindow: "Full request/response capture",
      maxOutput: "Real-time dashboard",
      cutoff: "Continuous observability",
      modalities: "Telemetry, Logs, Prompts",
      speed: "Asynchronous zero-blocking SDK",
      ttft: "10ms"
    }
  },
  {
    id: "open-webui",
    slug: "open-webui",
    name: "Open WebUI",
    org: "Open WebUI Community",
    category: "Productivity",
    entityType: "tool",
    rank: 29,
    rankDelta: "+5",
    superpower: "Self-Hosted ChatGPT Interface",
    superpowerShort: "Self-Hosted WebUI",
    superpowerDetail: "Feature-rich extensible WebUI for Ollama and OpenAI APIs",
    isOpenWeights: true,
    licenseType: "MIT",
    license: "MIT",
    arenaElo: null,
    eloChange: null,
    categoryMetricLabel: "Tool Rating",
    categoryMetricValue: "4.9 / 5.0",
    categorySubMetricLabel: "Adoption",
    categorySubMetricValue: "65k+ Stars",
    categoryDimension3: "Self-Hosted UI",
    mmluPro: "N/A",
    codingScore: "N/A",
    mathScore: "N/A",
    monthlyVisits: "16.4M",
    growth: "+95.0%",
    growthTrend: "up",
    price: "Free / Open Source",
    outputSpeed: "Instant Web",
    speedNum: 102,
    contextWindow: "Multi-session context",
    badge: "Open Source",
    shortDescription: "Extensible, self-hosted AI interface that operates entirely offline with Ollama, vLLM, and OpenAI-compatible backends.",
    fullDescription: "Open WebUI offers a polished ChatGPT-like interface featuring multimodal vision chat, document RAG, Python code execution, and granular role management.",
    website: "https://github.com/open-webui/open-webui",
    logoText: "OpenWebUI",
    logoColor: "#6366F1",
    releaseDate: "December 2023",
    source: "Open Source Telemetry & GitHub",
    lastUpdated: "March 2026",
    keyFeatures: [
      "Seamless integration with Ollama and OpenAI-compatible endpoints",
      "Built-in RAG with web search and document vector embedding",
      "Voice input/output with WebRTC and TTS",
      "Role-based access control (RBAC) and user management"
    ],
    benchmarks: [
      { name: "Community Rating", score: "4.9 / 5.0", rank: "#1 Self-Hosted UI" }
    ],
    specs: {
      inputPrice: "Free Open Source",
      outputPrice: "Self-hosted hardware",
      contextWindow: "Full chat history and document indexing",
      maxOutput: "Markdown and code blocks",
      cutoff: "Local execution",
      modalities: "Chat, Code, Vision, Voice",
      speed: "Instant UI response",
      ttft: "35ms"
    }
  }
];

// Append the new tools inside the AI_TOOLS_DATA array right before the closing `];`
const endIdx = content.lastIndexOf('];');
const toolsJson = newTools.map(t => '  ' + JSON.stringify(t, null, 2).replace(/\n/g, '\n  ')).join(',\n');

const updated = content.slice(0, endIdx).trimEnd() + ',\n' + toolsJson + '\n];\n';
fs.writeFileSync(toolsPath, updated, 'utf8');

console.log('Successfully added 9 open source tools to toolsData.js!');
