import type { Task } from "./tasks-api";

export type PinnedTask = Task & { iconUrl?: string };

export const PINNED_TASKS: PinnedTask[] = [
  {
    id: "pinned-image-generation",
    slug: "image-generation",
    title: "Generate Images",
    description: "Create stunning visuals and artwork from text prompts using state-of-the-art AI models.",
    difficulty: "EASY",
    pricingModel: "FREEMIUM",
    isFeatured: true,
    category: { slug: "image-creation", name: "Image Creation" },
    creator: null,
    createdAt: "2026-01-15T00:00:00Z",
    likes: 3120,
    subscribers: 48200,
    saves: 4210,
    resources: 12,
    tools: 27,
    models: 6,
    robots: 0,
    devices: 0,
    iconUrl: "https://www.google.com/s2/favicons?domain=midjourney.com&sz=64",
  },
  {
    id: "pinned-text-generation",
    slug: "write-content",
    title: "Write Content",
    description: "Draft articles, emails, stories, and marketing copy with AI writing assistants.",
    difficulty: "EASY",
    pricingModel: "FREEMIUM",
    isFeatured: true,
    category: { slug: "content-creation", name: "Content Creation" },
    creator: null,
    createdAt: "2026-01-15T00:00:00Z",
    likes: 4790,
    subscribers: 61300,
    saves: 5830,
    resources: 8,
    tools: 8,
    models: 3,
    robots: 0,
    devices: 0,
    iconUrl: "https://www.google.com/s2/favicons?domain=chat.openai.com&sz=64",
  },
  {
    id: "pinned-video-generation",
    slug: "generate-videos",
    title: "Generate Videos",
    description: "Turn text and images into AI-generated video clips, avatars, and short films.",
    difficulty: "MEDIUM",
    pricingModel: "PAID",
    isFeatured: true,
    category: { slug: "video-creation", name: "Video Creation" },
    creator: null,
    createdAt: "2026-01-15T00:00:00Z",
    likes: 2580,
    subscribers: 33900,
    saves: 3110,
    resources: 6,
    tools: 6,
    models: 1,
    robots: 0,
    devices: 0,
    iconUrl: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=64",
  },
  {
    id: "pinned-coding",
    slug: "write-code",
    title: "Write & Debug Code",
    description: "Generate, review, and debug code with AI pair-programming assistants.",
    difficulty: "ADVANCED",
    pricingModel: "FREEMIUM",
    isFeatured: true,
    category: { slug: "coding", name: "Coding" },
    creator: null,
    createdAt: "2026-01-15T00:00:00Z",
    likes: 5310,
    subscribers: 72100,
    saves: 6120,
    resources: 9,
    tools: 4,
    models: 2,
    robots: 0,
    devices: 0,
    iconUrl: "https://www.google.com/s2/favicons?domain=github.com&sz=64",
  },
];